spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Studentdb?retryWrites=true&writeConcern=majority

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis
    cache-name: students
